<?php
require_once('../auth/session_check.php');
require_once('../config/database.php');
requireAdmin();

$conn = getDBConnection();
$current_user = getCurrentUser();

$action = isset($_GET['action']) ? $_GET['action'] : '';
$start_date = isset($_GET['start_date']) ? $_GET['start_date'] : date('Y-m-01');
$end_date = isset($_GET['end_date']) ? $_GET['end_date'] : date('Y-m-t');

if ($action == 'export_csv') {
    // Get financial data
    $financial_query = "SELECT 
                        SUM(CASE WHEN md.status = 'unpaid' THEN md.amount ELSE 0 END) as unpaid,
                        SUM(CASE WHEN md.status = 'overdue' THEN md.amount ELSE 0 END) as overdue,
                        SUM(CASE WHEN md.status = 'paid' THEN md.amount ELSE 0 END) as paid,
                        SUM(md.amount) as total
                        FROM monthly_dues md
                        WHERE md.due_date BETWEEN ? AND ?";
    $stmt = $conn->prepare($financial_query);
    $stmt->bind_param("ss", $start_date, $end_date);
    $stmt->execute();
    $financial = $stmt->get_result()->fetch_assoc();

    // Get collection data
    $collection_query = "SELECT 
                         SUM(CASE WHEN md.status = 'paid' THEN 1 ELSE 0 END) as paid_count,
                         SUM(CASE WHEN md.status = 'unpaid' THEN 1 ELSE 0 END) as unpaid_count,
                         SUM(CASE WHEN md.status = 'overdue' THEN 1 ELSE 0 END) as overdue_count
                         FROM monthly_dues md
                         WHERE md.due_date BETWEEN ? AND ?";
    $stmt = $conn->prepare($collection_query);
    $stmt->bind_param("ss", $start_date, $end_date);
    $stmt->execute();
    $collection = $stmt->get_result()->fetch_assoc();

    // Get transactions
    $transactions_query = "SELECT p.payment_id, p.payment_date, p.amount_paid, p.payment_method, 
                          h.unit_number, CONCAT(u.first_name, ' ', u.last_name) as resident_name,
                          md.due_month, md.due_year
                          FROM payments p
                          INNER JOIN households h ON p.household_id = h.household_id
                          INNER JOIN household_members hm ON h.household_id = hm.household_id AND hm.is_primary = 1
                          INNER JOIN users u ON hm.user_id = u.user_id
                          INNER JOIN monthly_dues md ON p.dues_id = md.dues_id
                          WHERE p.payment_date BETWEEN ? AND ?
                          ORDER BY p.payment_date DESC";
    $stmt = $conn->prepare($transactions_query);
    $stmt->bind_param("ss", $start_date, $end_date);
    $stmt->execute();
    $transactions = $stmt->get_result();

    // Get debtors
    $debtors_query = "SELECT h.unit_number, CONCAT(u.first_name, ' ', u.last_name) as resident_name, 
                     SUM(md.amount) as total_debt
                     FROM household_members hm
                     INNER JOIN households h ON hm.household_id = h.household_id
                     INNER JOIN users u ON hm.user_id = u.user_id
                     INNER JOIN monthly_dues md ON h.household_id = md.household_id
                     WHERE md.status IN ('unpaid', 'overdue') AND hm.is_primary = 1
                     GROUP BY h.household_id
                     ORDER BY total_debt DESC";
    $debtors = $conn->query($debtors_query);

    // Create CSV
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="HOA_Report_' . date('Y-m-d') . '.csv"');

    $output = fopen('php://output', 'w');
    
    // BOM for Excel UTF-8
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

    // Summary Section
    fputcsv($output, ['HOA REPORT SUMMARY']);
    fputcsv($output, ['Report Period', $start_date . ' to ' . $end_date]);
    fputcsv($output, ['Generated Date', date('Y-m-d H:i:s')]);
    fputcsv($output, ['Generated By', $current_user['full_name']]);
    fputcsv($output, []);

    // Financial Summary
    fputcsv($output, ['FINANCIAL SUMMARY']);
    fputcsv($output, ['Metric', 'Amount']);
    fputcsv($output, ['Total Dues', number_format($financial['total'] ?? 0, 2)]);
    fputcsv($output, ['Total Paid', number_format($financial['paid'] ?? 0, 2)]);
    fputcsv($output, ['Unpaid Amount', number_format($financial['unpaid'] ?? 0, 2)]);
    fputcsv($output, ['Overdue Amount', number_format($financial['overdue'] ?? 0, 2)]);
    fputcsv($output, []);

    // Collection Status
    fputcsv($output, ['COLLECTION STATUS']);
    fputcsv($output, ['Status', 'Count']);
    fputcsv($output, ['Paid Accounts', $collection['paid_count'] ?? 0]);
    fputcsv($output, ['Unpaid Accounts', $collection['unpaid_count'] ?? 0]);
    fputcsv($output, ['Overdue Accounts', $collection['overdue_count'] ?? 0]);
    fputcsv($output, []);

    // Recent Transactions
    fputcsv($output, ['RECENT TRANSACTIONS']);
    fputcsv($output, ['Date', 'Unit', 'Resident Name', 'Amount', 'Payment Method', 'Month/Year']);
    
    if ($transactions && $transactions->num_rows > 0) {
        while ($transaction = $transactions->fetch_assoc()) {
            fputcsv($output, [
                $transaction['payment_date'],
                $transaction['unit_number'],
                $transaction['resident_name'],
                number_format($transaction['amount_paid'], 2),
                $transaction['payment_method'],
                $transaction['due_month'] . ' ' . $transaction['due_year']
            ]);
        }
    }
    fputcsv($output, []);

    // Top Debtors
    fputcsv($output, ['TOP DEBTORS']);
    fputcsv($output, ['Unit', 'Resident Name', 'Total Debt']);
    
    if ($debtors && $debtors->num_rows > 0) {
        while ($debtor = $debtors->fetch_assoc()) {
            fputcsv($output, [
                $debtor['unit_number'],
                $debtor['resident_name'],
                number_format($debtor['total_debt'], 2)
            ]);
        }
    }

    fclose($output);
    exit();
} else {
    header("Location: reports.php?error=invalid_action");
    exit();
}

$conn->close();
?>
